package com.csd63.postsapi.model;

import javax.persistence.*;

@Entity(name = "tbl_posts")
public class Post {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;
//    private String title;
    private String body;
    @Column(insertable = false, updatable = false) private String time; //Auto generated by DB
    private String author;
    private int likes;

    public Post() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

//    public String getTitle() {
//        return title;
//    }
//
//    public void setTitle(String title) {
//        this.title = title;
//    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

//    public String getImages() {
//        return images;
//    }
//
//    public void setImages(String images) {
//        if(images == null){
//            this.images = "default.jpg";
//        } else {
//            this.images = images;
//        }
//    }

    public int getLikes() {
        return likes;
    }

    public void setLikes(int likes) {
        this.likes = likes;
    }
}
